# Generated by Django 5.1.7 on 2025-03-22 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Doctor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                ("especialidade", models.CharField(max_length=200)),
                ("crm", models.CharField(max_length=50)),
                ("cidade", models.CharField(max_length=100)),
                ("estado", models.CharField(max_length=2)),
                ("visualizacoes", models.IntegerField(default=0)),
                (
                    "descricao",
                    models.TextField(
                        help_text="Médica formada pela Unesp Botucatu, com especialização em psicanálise e ênfase no tratamento da dor crônica. Pós-graduada em Cannabis Sativa pela Sbec e certificada internacionalmente em cannabis pela WeCann Academy. Completou a Capacitação em Cannabis Medicinal pela USP-SP e Unicamp."
                    ),
                ),
                (
                    "patologias",
                    models.TextField(
                        help_text="Lista de patologias, separadas por vírgula."
                    ),
                ),
                (
                    "atendimento",
                    models.TextField(
                        help_text="Grupos atendidos (ex: Crianças, Adolescentes, Adultos e Idosos)."
                    ),
                ),
                ("convenio", models.BooleanField(default=False)),
                (
                    "retorno_e_acompanhamento",
                    models.CharField(
                        blank=True,
                        help_text="Ex: 'Retorno em até 30 dias'",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "experiencia_prescricao",
                    models.CharField(
                        blank=True,
                        help_text="Ex: 'Não informado' ou 'Sim', conforme o caso",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "formacao",
                    models.TextField(
                        blank=True,
                        help_text="Exemplo: 'UNESP - Graduação em Medicina; Sbec - Pós-graduação em Cannabis Sativa'",
                        null=True,
                    ),
                ),
                (
                    "foto",
                    models.ImageField(blank=True, null=True, upload_to="doctors/"),
                ),
            ],
        ),
    ]
