# Generated by Django 5.1.7 on 2025-03-22 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_retorno_e_acompanhamento_doctor_retorno_acompanhamento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='duracao_consulta',
            field=models.IntegerField(default='00', help_text='Duração da consulta em minutos'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='preco_consulta',
            field=models.DecimalField(decimal_places=2, default='00.00', max_digits=8),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='descricao',
            field=models.TextField(help_text='Descreva a pessoa do médico.'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='experiencia_prescricao',
            field=models.CharField(blank=True, help_text="Ex: 'Sim' ou 'Não' ou 'Não informado'", max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='formacao',
            field=models.TextField(blank=True, help_text='Onde se formou e suas especialidades', null=True),
        ),
    ]
