# Generated by Django 5.1.7 on 2025-03-25 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_doctor_duracao_consulta_doctor_preco_consulta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='atendimento',
            field=models.TextField(default='Não informado', help_text='Grupos atendidos (ex: Crianças, Adolescentes, Adultos e Idosos).', null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='descricao',
            field=models.TextField(default='Não informado', help_text='Descreva a pessoa do médico.', null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='experiencia_prescricao',
            field=models.CharField(blank=True, default='Não informado', help_text="Ex: 'Sim' ou 'Não' ou 'Não informado'", max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='formacao',
            field=models.TextField(blank=True, default='Não informado', help_text='Onde se formou e suas especialidades', null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='patologias',
            field=models.TextField(default='Não informado', help_text='Lista de patologias, separadas por vírgula.', null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='retorno_acompanhamento',
            field=models.CharField(blank=True, default='Não informado', help_text="Ex: 'Retorno em até 30 dias'", max_length=100, null=True),
        ),
    ]
