# Generated by Django 5.1.7 on 2025-04-19 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_doctor_atendimento_alter_doctor_descricao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
