# Generated by Django 5.1.7 on 2025-04-19 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_doctor_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='doctors/'),
        ),
    ]
